/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.milaifontanals.equip.vista;

import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.milaifontanals.equip.interficiepersistencia.GestorBDEquipException;

import org.milaifontanals.equip.model.*;

/**
 * @author MAVI
 */
public class VistaJugador extends javax.swing.JFrame {
    private List<JRadioButton> rbList = new ArrayList<>();
    private String[] tableTitles= new String[]{"ID","Equip","Temporada","Categ.","Tipus","Eliminar Titularitat"};
    private Jugador jugSel;
    private Jugador jugAux=new Jugador(); //equip auxiliar per fer tracking dels canvis
    private boolean existeix;
    private MainPage mp;
    DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
    JFormattedTextField txtDate = new JFormattedTextField(df);
    
    public VistaJugador(int idJug, MainPage view) {
        //si s'ha pasat un id == -1 vol dir que esta creant un nou jugador
        existeix=(idJug==-1)?false:true;
        mp=view;
        //si no es un alta guardem recuperem la informació del jugador
        if(existeix){
            try {
                jugSel=Constants.getgBD().infoJugador(idJug);
                jugAux=jugSel;
            } catch (GestorBDEquipException ex) {
                errGJ.setText(ex.getMessage());
            }
        }else{
            jugSel=new Jugador();
        }
        initComponents();
        carregarLlistatRb();
        prepararFinestra();
        crearTableModel();
    }
    //aquet programa s'ha fet perque hem costa controlar la List de Titulars
    public void carregarLlistatRb(){
        rbList.add(rbFem);
        rbList.add(rbMasc);
    }
    public void activarBotonsiCerca(){
        //únicament estarán abilitats aquest botons si el jugador es nou
        eliminarJugador.setVisible(existeix);
        guardarCanvis.setEnabled(existeix);
        idLegal.setEnabled(existeix);
    }
    //preparem l'informació de la finestra
    public void prepararFinestra(){
        actualitzarTitol();
        activarBotonsiCerca();
        buttonGroup.add(rbMasc);
        buttonGroup.add(rbFem);
        sexeDefault();
    }
    public void actualitzarTitol(){
        //titol per default si es una alta nova
        String titol = "Alta Jugador";
        if(existeix){
            String nomJug=jugSel.getNom();
            titol="Edició Jugador - "+nomJug;
            nom.setText(nomJug);
        }
        titolLabel.setText(titol); //fiquel el titol
        dataNaix.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
              char c = e.getKeyChar();
              if (!((c >= '0') && (c <= '9') ||
                 (c == KeyEvent.VK_BACK_SPACE) ||
                 (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_SLASH)))        
              {
                JOptionPane.showMessageDialog(null, "Please Enter Valid");
                e.consume();
              }
            }
        });
    }
    public void sexeDefault(){
        //si es una modificació d'un equip o l'equiup s'ha donat d'alta fixem la categoria
        if(existeix){
            char tipus=jugSel.getSexe();
            //seleccionem la categoria
            int i=0;
            while(rbList.get(i).getName().charAt(0)!=tipus && i!=rbList.size()){
                i++;
            }
            rbList.get(i).setSelected(existeix);
        }else{
            rbMasc.setSelected(true);
            jugAux.setSexe(rbMasc.getName().charAt(0));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        logOut = new javax.swing.JButton();
        tornar = new javax.swing.JButton();
        infoEquip = new javax.swing.JPanel();
        nomLabel = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        sexeLabel = new javax.swing.JLabel();
        guardarCanvis = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        eqTable = new javax.swing.JTable();
        rbMasc = new javax.swing.JRadioButton();
        rbFem = new javax.swing.JRadioButton();
        idLegalLable = new javax.swing.JLabel();
        cognomLabel = new javax.swing.JLabel();
        idLegal = new javax.swing.JTextField();
        cognom = new javax.swing.JTextField();
        dNaixLabel = new javax.swing.JLabel();
        iban = new javax.swing.JTextField();
        adrecaLabel = new javax.swing.JLabel();
        poblacioLabel = new javax.swing.JLabel();
        cpLabel = new javax.swing.JLabel();
        idLegal1 = new javax.swing.JTextField();
        idLegal2 = new javax.swing.JTextField();
        idLegal3 = new javax.swing.JTextField();
        dRevMedLabel = new javax.swing.JLabel();
        dataNaix = new javax.swing.JTextField();
        dataRevMed = new javax.swing.JTextField();
        feta = new javax.swing.JCheckBox();
        ibanLabel1 = new javax.swing.JLabel();
        pujarFoto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        errGJ = new javax.swing.JLabel();
        eliminarJugador = new javax.swing.JButton();
        titolLabel = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        logOut.setBackground(new java.awt.Color(0, 153, 51));
        logOut.setFont(new java.awt.Font("Bauhaus 93", 0, 12)); // NOI18N
        logOut.setForeground(new java.awt.Color(255, 255, 255));
        logOut.setText("Log-out");
        logOut.setAlignmentX(0.5F);
        logOut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOut(evt);
            }
        });

        tornar.setBackground(new java.awt.Color(0, 153, 51));
        tornar.setFont(new java.awt.Font("Bauhaus 93", 0, 12)); // NOI18N
        tornar.setForeground(new java.awt.Color(255, 255, 255));
        tornar.setText("Tornar a Menú");
        tornar.setAlignmentX(0.5F);
        tornar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tornar.setName("gj"); // NOI18N
        tornar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tornar(evt);
            }
        });

        infoEquip.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)), "INFORMACIO DEL JUGADOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bauhaus 93", 0, 14), new java.awt.Color(0, 153, 0))); // NOI18N
        infoEquip.setMaximumSize(new java.awt.Dimension(782, 297));
        infoEquip.setMinimumSize(new java.awt.Dimension(782, 297));

        nomLabel.setFont(new java.awt.Font("Bauhaus 93", 0, 14)); // NOI18N
        nomLabel.setText("Nom:");

        nom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nom.setName("nom"); // NOI18N
        nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                controlNom(evt);
            }
        });

        sexeLabel.setFont(new java.awt.Font("Bauhaus 93", 0, 14)); // NOI18N
        sexeLabel.setText("*Sexe:");

        guardarCanvis.setBackground(new java.awt.Color(0, 153, 51));
        guardarCanvis.setFont(new java.awt.Font("Bauhaus 93", 0, 12)); // NOI18N
        guardarCanvis.setForeground(new java.awt.Color(255, 255, 255));
        guardarCanvis.setText("Guardar");
        guardarCanvis.setToolTipText("");
        guardarCanvis.setAlignmentX(0.5F);
        guardarCanvis.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        guardarCanvis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarCanvis(evt);
            }
        });

        eqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        eqTable.setGridColor(new java.awt.Color(51, 153, 0));
        eqTable.setMaximumSize(new java.awt.Dimension(300, 80));
        eqTable.setMinimumSize(new java.awt.Dimension(300, 80));
        eqTable.setName("eqTable"); // NOI18N
        eqTable.setShowVerticalLines(true);
        jScrollPane1.setViewportView(eqTable);

        rbMasc.setText("Masculí");
        rbMasc.setName("H"); // NOI18N
        rbMasc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccioItem(evt);
            }
        });

        rbFem.setText("Femení");
        rbFem.setName("D"); // NOI18N
        rbFem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccioItem(evt);
            }
        });

        idLegalLable.setFont(new java.awt.Font("Bauhaus 93", 0, 14)); // NOI18N
        idLegalLable.setText("NIE/NIF:");

        cognomLabel.setFont(new java.awt.Font("Bauhaus 93", 0, 14)); // NOI18N
        cognomLabel.setText("Cognom:");

        idLegal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        idLegal.setName("nom"); // NOI18N
        idLegal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idLegalcontrolNom(evt);
            }
        });

        cognom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cognom.setName("nom"); // NOI18N
        cognom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cognomcontrolNom(evt);
            }
        });

        dNaixLabel.setFont(new java.awt.Font("Bauhaus 93", 0, 14)); // NOI18N
        dNaixLabel.setText("*Data Naix.:");

        iban.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        iban.setName("nom"); // NOI18N
        iban.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ibancontrolNom(evt);
            }
        });

        adrecaLabel.setFont(new java.awt.Font("Bauhaus 93", 0, 14)); // NOI18N
        adrecaLabel.setText("Adreça:");

        poblacioLabel.setFont(new java.awt.Font("Bauhaus 93", 0, 14)); // NOI18N
        poblacioLabel.setText("Població:");

        cpLabel.setFont(new java.awt.Font("Bauhaus 93", 0, 14)); // NOI18N
        cpLabel.setText("Codi Postal:");

        idLegal1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        idLegal1.setName("nom"); // NOI18N
        idLegal1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idLegal1controlNom(evt);
            }
        });

        idLegal2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        idLegal2.setName("nom"); // NOI18N
        idLegal2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idLegal2controlNom(evt);
            }
        });

        idLegal3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        idLegal3.setName("nom"); // NOI18N
        idLegal3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idLegal3controlNom(evt);
            }
        });

        dRevMedLabel.setFont(new java.awt.Font("Bauhaus 93", 0, 14)); // NOI18N
        dRevMedLabel.setText("Data Rev.Medica:");

        dataNaix.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dataNaix.setName("nom"); // NOI18N
        dataNaix.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dataNaixcontrolNom(evt);
            }
        });

        dataRevMed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dataRevMed.setName("nom"); // NOI18N
        dataRevMed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dataRevMedcontrolNom(evt);
            }
        });

        feta.setForeground(new java.awt.Color(51, 153, 0));
        feta.setEnabled(false);

        ibanLabel1.setFont(new java.awt.Font("Bauhaus 93", 0, 14)); // NOI18N
        ibanLabel1.setText("IBAN:");

        pujarFoto.setBackground(new java.awt.Color(0, 153, 51));
        pujarFoto.setFont(new java.awt.Font("Bauhaus 93", 0, 12)); // NOI18N
        pujarFoto.setForeground(new java.awt.Color(255, 255, 255));
        pujarFoto.setText("Pujar Foto");
        pujarFoto.setToolTipText("");
        pujarFoto.setAlignmentX(0.5F);
        pujarFoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pujarFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pujarFoto(evt);
            }
        });

        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 1, true));

        errGJ.setForeground(new java.awt.Color(255, 0, 0));
        errGJ.setName("errGJ"); // NOI18N

        javax.swing.GroupLayout infoEquipLayout = new javax.swing.GroupLayout(infoEquip);
        infoEquip.setLayout(infoEquipLayout);
        infoEquipLayout.setHorizontalGroup(
            infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoEquipLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoEquipLayout.createSequentialGroup()
                        .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLegalLable)
                            .addComponent(cognomLabel)
                            .addComponent(nomLabel))
                        .addGap(32, 32, 32)
                        .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cognom, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(nom)
                            .addComponent(idLegal)))
                    .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(infoEquipLayout.createSequentialGroup()
                            .addComponent(sexeLabel)
                            .addGap(57, 57, 57)
                            .addComponent(rbMasc)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbFem))
                        .addGroup(infoEquipLayout.createSequentialGroup()
                            .addComponent(dNaixLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dataNaix, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(infoEquipLayout.createSequentialGroup()
                            .addComponent(ibanLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(iban, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoEquipLayout.createSequentialGroup()
                            .addComponent(pujarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42)
                .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoEquipLayout.createSequentialGroup()
                        .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dRevMedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLegal1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataRevMed, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoEquipLayout.createSequentialGroup()
                        .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(infoEquipLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, infoEquipLayout.createSequentialGroup()
                                .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(poblacioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adrecaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(infoEquipLayout.createSequentialGroup()
                                        .addComponent(idLegal2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                        .addComponent(guardarCanvis, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(feta)
                                        .addComponent(idLegal3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(23, 23, 23))))
            .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoEquipLayout.createSequentialGroup()
                    .addContainerGap(337, Short.MAX_VALUE)
                    .addComponent(errGJ, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(22, 22, 22)))
        );
        infoEquipLayout.setVerticalGroup(
            infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoEquipLayout.createSequentialGroup()
                .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(guardarCanvis, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idLegalLable)
                        .addComponent(idLegal, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idLegal2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(adrecaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(poblacioLabel)
                    .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomLabel)
                        .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(idLegal3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoEquipLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cognomLabel)
                            .addComponent(cognom, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(infoEquipLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpLabel)
                            .addComponent(idLegal1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoEquipLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(feta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dRevMedLabel)
                                .addComponent(dataRevMed, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(infoEquipLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sexeLabel)
                            .addComponent(rbMasc)
                            .addComponent(rbFem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dNaixLabel)
                            .addComponent(dataNaix, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iban, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ibanLabel1))))
                .addGap(18, 18, 18)
                .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pujarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(infoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(infoEquipLayout.createSequentialGroup()
                    .addGap(148, 148, 148)
                    .addComponent(errGJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(146, 146, 146)))
        );

        eliminarJugador.setBackground(new java.awt.Color(0, 153, 51));
        eliminarJugador.setFont(new java.awt.Font("Bauhaus 93", 0, 12)); // NOI18N
        eliminarJugador.setForeground(new java.awt.Color(255, 255, 255));
        eliminarJugador.setText("Eliminar Jugador");
        eliminarJugador.setToolTipText("");
        eliminarJugador.setAlignmentX(0.5F);
        eliminarJugador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminarJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarJugador(evt);
            }
        });

        titolLabel.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        titolLabel.setForeground(new java.awt.Color(0, 153, 0));
        titolLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titolLabel.setText("jLabel1");

        infoLabel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        infoLabel.setForeground(new java.awt.Color(102, 102, 102));
        infoLabel.setText("* camps nomès modificables si el jugador no pertany a cap equip");
        infoLabel.setName("infoLabel"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoEquip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tornar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eliminarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(titolLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(titolLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(infoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tornar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminarJugador)
                        .addGap(16, 16, 16)))
                .addComponent(infoEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        tornar.getAccessibleContext().setAccessibleName("gj");
        tornar.getAccessibleContext().setAccessibleDescription("gj");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void tornar(java.awt.event.MouseEvent evt) {                        
        deixemLaFinestra();
    }   
    private void eliminarJugador(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarJugador
        boolean err=false;
        try {
            Constants.getgBD().eliminarJugador(jugSel.getId());
        } catch (GestorBDEquipException ex) {
            errGJ.setText(ex.getMessage());
            err=true;
        }
        //si no hi ha error al eliminar demanem confirmació
        if(!err){
            confirmacióEliminar();
        }
    }//GEN-LAST:event_eliminarJugador

    private void pujarFoto(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pujarFoto
        // TODO add your handling code here:
    }//GEN-LAST:event_pujarFoto

    private void dataRevMedcontrolNom(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dataRevMedcontrolNom
        // TODO add your handling code here:
    }//GEN-LAST:event_dataRevMedcontrolNom

    private void dataNaixcontrolNom(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dataNaixcontrolNom
        // TODO add your handling code here:
    }//GEN-LAST:event_dataNaixcontrolNom

    private void idLegal3controlNom(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idLegal3controlNom
        // TODO add your handling code here:
    }//GEN-LAST:event_idLegal3controlNom

    private void idLegal2controlNom(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idLegal2controlNom
        // TODO add your handling code here:
    }//GEN-LAST:event_idLegal2controlNom

    private void idLegal1controlNom(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idLegal1controlNom
        // TODO add your handling code here:
    }//GEN-LAST:event_idLegal1controlNom

    private void ibancontrolNom(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ibancontrolNom
        // TODO add your handling code here:
    }//GEN-LAST:event_ibancontrolNom

    private void cognomcontrolNom(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cognomcontrolNom
        // TODO add your handling code here:
    }//GEN-LAST:event_cognomcontrolNom

    private void idLegalcontrolNom(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idLegalcontrolNom
        // TODO add your handling code here:
    }//GEN-LAST:event_idLegalcontrolNom

    private void seleccioItem(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccioItem
        String tipus=evt.getComponent().getName();
        jugAux.setSexe(tipus.charAt(0));
        activarGuardar();
    }//GEN-LAST:event_seleccioItem

    private void guardarCanvis(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarCanvis
        String err="";
        int equipNou=Optional.ofNullable(jugSel.getId()).orElse(0);
        try {
            if(equipNou == 0){
                Constants.getgBD().afegirJugador(jugSel);
            }else{
                Constants.getgBD().modificarJugador(jugSel);
            }
        } catch (GestorBDEquipException ex) {
            err=ex.getMessage();
        }
        confirmarCanvis(err);
        //cambiarem el titol únicament si es un equip nou i ara existeix
        if(equipNou==0){
            try {
                jugSel.setId(Constants.getgBD().idJugador(jugSel.getId_legal()));
                existeix=true; //ara el jugador existeix
                prepararFinestra();
            } catch (GestorBDEquipException ex) {
                err=ex.getMessage();
            }
        }

        if(err.isBlank()){
            crearTableModel();
        }
    }//GEN-LAST:event_guardarCanvis

    private void controlNom(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_controlNom
        String err=jugSel.setNom(nom.getText());
        errGJ.setText(err);
        activarGuardar();
    }//GEN-LAST:event_controlNom

//GEN-FIRST:event_tornar
 
//GEN-LAST:event_tornar

    private void logOut(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOut
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_logOut
    private void confirmarCanvis(String err){
        try {
            errGJ.setText(err);
            if(err.isBlank()){
                Constants.getgBD().confirmarCanvis();
            }else{
                Constants.getgBD().desferCanvis();
            }
        } catch (GestorBDEquipException ex) {
            errGJ.setText(ex.getMessage());
        }
    }
    public void deixemLaFinestra(){
        this.dispose();
        mp.setVisible(true);
    }
    private void activarGuardar(){
        /*boolean activarGuardar=false;
        if(eqSel.getNom()!=null && errGJ.getText().isEmpty()){
            activarGuardar=true;
        }
        guardarCanvis.setEnabled(activarGuardar);
        Boolean enabled=true;
        if(eqSel.getTipus()!=jugAux.getTipus() || eqSel.getCat()!=jugAux.getCat()){
            enabled=false;
        }
        guardarTitulars.setEnabled(enabled);
        jugTable.setEnabled(enabled);*/
    }            //programa per guardar titulars
    //creem dinámicament la taula
    private void crearTableModel(){
        int numColumns=tableTitles.length;
        DefaultTableModel mt= new DefaultTableModel(new Object[0][tableTitles.length],tableTitles);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        errGJ.setText("");//ens asegurem que no queda cap error a la finestra
        eqTable.setModel(mt);//setejem columnes
        //amagem la columna ID que la farem servir per a eliminar/
        eqTable.removeColumn(eqTable.getColumnModel().getColumn(0));
        if(existeix){
            try {
                //Centrem les columnes necesaries (Categoria, tipus, te jugadors):
                for(int i=3; i<(numColumns-1);i++){
                    eqTable.getColumnModel().getColumn(i).setCellRenderer( centerRenderer );
                }
                //carregemm els equips als que juga
                List<Equip> equipParticipa =Constants.getgBD().llistatEquipParticipa(jugSel.getId());
                for(Equip e : equipParticipa){
                    Object[] info= new Object[]{
                        e.getId(),
                        e.getNom(),
                        e.getTemp(),
                        Constants.tipusNom(e.getTipus()),
                        Constants.nomCategoria(e.getCat()),
                        "Eliminar"
                        };
                    mt.addRow(info);
                }
                taulaConfiguration(eqTable,4);
            } catch (GestorBDEquipException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "InfoBox: " + "DB Connection Error", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }
    private void taulaConfiguration(JTable t, int del){
        t.setAutoCreateRowSorter(true);
        ButtonColumn buttonDel= new ButtonColumn(t,delTitularitat,del);
    }
    Action delTitularitat= new AbstractAction(){
        public void actionPerformed(ActionEvent e){
            JTable table = (JTable)e.getSource(); 
            String tName= table.getName();
            int row = Integer.valueOf( e.getActionCommand() );
            int id= Integer.valueOf(((DefaultTableModel)table.getModel()).getValueAt(row, 1).toString());
            String nom= ((DefaultTableModel)table.getModel()).getValueAt(row, 2).toString();
            Boolean err=false;
            try {
                Constants.getgBD().eliminarTitular(new Titular(id,jugSel.getId(),false));
            } catch (GestorBDEquipException ex) {
                errGJ.setText(ex.getMessage());
                err=true;
            }
            //si no hi ha hagut capp error en intentar eliminar el jugador/equip
            if(!err){
                //demanem confirmació abans d'eliminar, si tot ha anat bé retorna 0
                if(confirmacióEliminarTitularitat(nom, tName)==0 && !err){
                    //si confirma, després de fer el delete a la BBDD, ens carregem la row.
                    ((DefaultTableModel)table.getModel()).removeRow(row);
                }
            }

        }
    };
    private int confirmacióEliminarTitularitat(String nom, String tName){
        int resposta=JOptionPane.showConfirmDialog(null, "Estas segur que vols que el jugador "+jugSel.getNom()+"deixi de ser titular de l'equip "+nom+"?", "Compte!",
			JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        String err="";
        try {
            if(resposta==0){
                Constants.getgBD().confirmarCanvis();
            }else{
                Constants.getgBD().desferCanvis();
            }
        } catch (GestorBDEquipException ex) {
            err=ex.getMessage();
            resposta=1;
        }
        errGJ.setText(err);
        return resposta;
    }
    private void confirmacióEliminar(){
        int resposta=JOptionPane.showConfirmDialog(null, "Estas segur que vols eliminar el jugador "+jugSel.getNom()+"?", "Compte!",
			JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        String err="";
        if(resposta==0){
            try {
                Constants.getgBD().confirmarCanvis();
                deixemLaFinestra();
            } catch (GestorBDEquipException ex) {
                err=ex.getMessage();
                resposta=1;
            }
        }else{
            try {
                Constants.getgBD().desferCanvis();
            } catch (GestorBDEquipException ex) {
                 err=ex.getMessage();
                 resposta=1;
            }
        }
        errGJ.setText(err);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adrecaLabel;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JTextField cognom;
    private javax.swing.JLabel cognomLabel;
    private javax.swing.JLabel cpLabel;
    private javax.swing.JLabel dNaixLabel;
    private javax.swing.JLabel dRevMedLabel;
    private javax.swing.JTextField dataNaix;
    private javax.swing.JTextField dataRevMed;
    private javax.swing.JButton eliminarJugador;
    private javax.swing.JTable eqTable;
    private javax.swing.JLabel errGJ;
    private javax.swing.JCheckBox feta;
    private javax.swing.JButton guardarCanvis;
    private javax.swing.JTextField iban;
    private javax.swing.JLabel ibanLabel1;
    private javax.swing.JTextField idLegal;
    private javax.swing.JTextField idLegal1;
    private javax.swing.JTextField idLegal2;
    private javax.swing.JTextField idLegal3;
    private javax.swing.JLabel idLegalLable;
    private javax.swing.JPanel infoEquip;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logOut;
    private javax.swing.JTextField nom;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JLabel poblacioLabel;
    private javax.swing.JButton pujarFoto;
    private javax.swing.JRadioButton rbFem;
    private javax.swing.JRadioButton rbMasc;
    private javax.swing.JLabel sexeLabel;
    private javax.swing.JLabel titolLabel;
    private javax.swing.JButton tornar;
    // End of variables declaration//GEN-END:variables
}
